gText_Birch_Welcome::
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is PROF. BIRCH.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "We humans live alongside POKéMON.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_Nuzlocke::
	.string "Select difficulty.$"

gText_Birch_AreYouSure_Normal::
	.string "Are you sure?\n"
	.string "Classic POKéMON rules.$"

gText_Birch_AreYouSure_Hard::
	.string "Are you sure?\n"
	.string "SET mode, no items in battle,\l"
	.string "GYM level caps.$"

gText_Birch_AreYouSure_Hardcore::
	.string "Are you sure?\n"
	.string "Hard mode, but POKéMON can't\l"
	.string "be revived.$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"